local data=
{
    bulletType=1,
    bulletEffect=3,
    explosionRange=Vector3.New(300,300,300),
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.5,
        frequency=100,
        strength=2,
        rotX=7,
        rotY=7,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    hasDerive=false,
    trailVFXAssetID="sandboxId://PVZ_VFX/Prefab/SK_Garlic/Garlic_Trail.prefab",
    trailVFXScale=Vector3.New(1,1,1),
    hitVFXAssetID="sandboxId://PVZ_VFX/Prefab/SK_Garlic/Garlic_Brust.prefab",
    hitVFXScale=Vector3.New(1.5,1.5,1.5),
    hitGroundVFXAssetID="sandboxId://PVZ_VFX/Prefab/SK_Garlic/Garlic_Brust.prefab",
    hitGroundVFXScale=Vector3.New(1.5,1.5,1.5),
    hitSoundAssetID="sandboxId://PVZ_AU/Garlic/Garlic_hit.mp3",
    hitSoundAssetVolume=1,
    hitGroundSoundAssetID="",
    hitGroundSoundAssetVolume=1,
    parabolaSign=false,
    parabolaMaxDeg=0
}
return data