local data=
{
    BonusID=83,
    BonusPrerequisite=
    {
        82
    },
    BonusName="穿心针III",
    BonusCategory=2,
    BonusType=0,
    BonusPlantTarget=2,
    BonusPlantNameTargetValue="Cactus",
    BonusSelectType=0,
    BonusList=
    {
        {
            BonusValue=7,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=2,
            BonusHasDuration=false
        }
    },
    BonusQuality=1,
    BonusIcon="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441101.png",
    BonusDescription="仙人掌攻击可以穿透6名敌人",
    BonusFooter=""
}
return data