local data=
{
    plantType=0,
    maxHealth=100,
    damage=100,
    magazine=10,
    magazineCarry=200,
    bulletName="IcePea",
    bulletRange=8000,
    bulletSpeed=10000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/SKS_Fire.prefab",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441001.png",
    brief="发射冰冷豌豆减缓敌人步伐，是团队减速与控场的核心成员。"
}
return data