local data=
{
    BonusID=176,
    BonusPrerequisite=
    {
        175
    },
    BonusName="多胞胎III",
    BonusCategory=2,
    BonusType=0,
    BonusPlantTarget=2,
    BonusPlantNameTargetValue="CherryHowitzer",
    BonusSelectType=0,
    BonusList=
    {
        {
            BonusValue=2,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=5,
            BonusHasDuration=false
        },
        {
            BonusValue=3,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=6,
            BonusHasDuration=false
        }
    },
    BonusQuality=1,
    BonusIcon="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440401.png",
    BonusDescription="爆炸后会剩余三个小樱桃，2秒后再次爆炸造成150伤害",
    BonusFooter=""
}
return data