local data=
{
    plantType=1,
    maxHealth=100,
    damage=150,
    magazine=1,
    magazineCarry=25,
    bulletName="GarlicPea",
    bulletRange=10000,
    bulletSpeed=4000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/SK_Garlic/Garlic_Fire.prefab",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441401.png",
    brief="发射恶臭大蒜扰乱敌人视线与节奏，能打能控，气味相当致命。"
}
return data