local data=
{
    BonusID=132,
    BonusPrerequisite=
    {
        131
    },
    BonusName="玉米冲击波II",
    BonusCategory=2,
    BonusType=0,
    BonusPlantTarget=2,
    BonusPlantNameTargetValue="LaserCorn",
    BonusSelectType=0,
    BonusList=
    {
        {
            BonusValue=6,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=2,
            BonusHasDuration=false
        }
    },
    BonusQuality=1,
    BonusIcon="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440901.png",
    BonusDescription="玉米激光可以穿透6名僵尸",
    BonusFooter=""
}
return data