local data=
{
    bulletType=1,
    bulletEffect=0,
    explosionRange=Vector3.New(650,650,650),
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.7,
        frequency=200,
        strength=5,
        rotX=10,
        rotY=10,
        rotZ=0,
        posX=10,
        posY=10,
        posZ=0
    },
    hasDerive=false,
    trailVFXAssetID="sandboxId://PVZ_VFX/Prefab/CoconutRocket/CoconutRocket_Trail.prefab",
    trailVFXScale=Vector3.New(1,1,1),
    hitVFXAssetID="sandboxId://PVZ_VFX/Prefab/CoconutRocket/CoconutRocket_Brust.prefab",
    hitVFXScale=Vector3.New(1.8,1.8,1.8),
    hitGroundVFXAssetID="sandboxId://PVZ_VFX/Prefab/CoconutRocket/CoconutRocket_Brust.prefab",
    hitGroundVFXScale=Vector3.New(1.8,1.8,1.8),
    hitSoundAssetID="sandboxId://PVZ_AU/CoconutRocket/CoconutRocket_hit.mp3",
    hitSoundAssetVolume=1,
    hitGroundSoundAssetID="",
    hitGroundSoundAssetVolume=1,
    parabolaSign=false,
    parabolaMaxDeg=0
}
return data