local data=
{
    BonusID=82,
    BonusPrerequisite=
    {
        81
    },
    BonusName="穿心针II",
    BonusCategory=2,
    BonusType=0,
    BonusPlantTarget=2,
    BonusPlantNameTargetValue="Cactus",
    BonusSelectType=0,
    BonusList=
    {
        {
            BonusValue=5,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=2,
            BonusHasDuration=false
        }
    },
    BonusQuality=1,
    BonusIcon="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441101.png",
    BonusDescription="仙人掌攻击可以穿透4名敌人",
    BonusFooter=""
}
return data