local data=
{
    plantType=2,
    maxHealth=100,
    damage=150,
    magazine=1,
    magazineCarry=60,
    bulletName="CherryBomb",
    bulletRange=10000,
    bulletSpeed=2500,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/M79_Fire.prefab",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(0,0,0),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440401.png",
    brief="榴弹爆裂瞬间引燃战场，适合一发清场，是爆破控的最爱。"
}
return data