local data=
{
    plantType=0,
    maxHealth=100,
    damage=100,
    magazine=7,
    magazineCarry=-1,
    bulletName="BonkChoyPea",
    bulletRange=2000,
    bulletSpeed=8000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="",
    fireVFXScale=Vector3.New(0.5,0.5,0.5),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441201.png",
    brief="拳拳到肉的近战猛将，无限弹药搭配小范围攻击，近身压制力强。"
}
return data