local data=
{
    bulletType=1,
    bulletEffect=0,
    explosionRange=Vector3.New(600,600,600),
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.7,
        frequency=500,
        strength=7,
        rotX=15,
        rotY=15,
        rotZ=0,
        posX=10,
        posY=10,
        posZ=0
    },
    hasDerive=false,
    trailVFXAssetID="sandboxId://PVZ_VFX/Prefab/MortarPea/MortarPea_Trail.prefab",
    trailVFXScale=Vector3.New(1,1,1),
    hitVFXAssetID="sandboxId://PVZ_VFX/Prefab/MortarPea/MortarPea_Hit.prefab",
    hitVFXScale=Vector3.New(2.5,2.5,2.5),
    hitGroundVFXAssetID="sandboxId://PVZ_VFX/Prefab/MortarPea/MortarPea_Hit.prefab",
    hitGroundVFXScale=Vector3.New(2.5,2.5,2.5),
    hitSoundAssetID="sandboxId://PVZ_AU/BambooMortar/BambooMortar_hit.mp3",
    hitSoundAssetVolume=1,
    hitGroundSoundAssetID="",
    hitGroundSoundAssetVolume=1,
    parabolaSign=true,
    parabolaMaxDeg=70
}
return data