local data=
{
    miniPrice=500,
    gamePrice=50000,
    rewardList=
    {
        {
            rewardType=0,
            rewardCardQuality=4,
            rewardProbability=0.1,
            rewardCardCountMin=1,
            rewardCardCountMax=2
        },
        {
            rewardType=0,
            rewardCardQuality=3,
            rewardProbability=5,
            rewardCardCountMin=3,
            rewardCardCountMax=8
        },
        {
            rewardType=0,
            rewardCardQuality=2,
            rewardProbability=45,
            rewardCardCountMin=12,
            rewardCardCountMax=20
        },
        {
            rewardType=0,
            rewardCardQuality=1,
            rewardProbability=49.9,
            rewardCardCountMin=50,
            rewardCardCountMax=100
        },
        {
            rewardType=1,
            rewardCurrencyMin=700,
            rewardCurrencyMax=1000
        }
    }
}
return data