local data=
{
    plantType=0,
    maxHealth=100,
    damage=300,
    magazine=10,
    magazineCarry=90,
    bulletName="SplitPea",
    bulletRange=10000,
    bulletSpeed=10000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/AWP_Fire.prefab",
    fireVFXScale=Vector3.New(5,5,5),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441901.png",
    brief="配备狙击豌豆，远距离一击制敌。"
}
return data