local data=
{
    plantType=3,
    maxHealth=100,
    damage=120,
    magazine=30,
    magazineCarry=220,
    bulletName="FirebatPea",
    bulletRange=4000,
    bulletSpeed=6000,
    shootConfig=
    {
        needCharge=true,
        chargeTime=0.5,
        releaseToFire=false,
        chargeCooldownTime=0.5,
        isLoopFire=true,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/SK_FirebatPea/SK_FirebatPea_Shoot.prefab",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440801.png",
    brief="持续喷吐火焰灼烧敌人，适合清理密集目标，热血战场主角。"
}
return data