local data=
{
    plantType=0,
    maxHealth=100,
    damage=80,
    magazine=100,
    magazineCarry=600,
    bulletName="MachineGunPea",
    bulletRange=8000,
    bulletSpeed=10000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=0.5,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/MG42_Fire.prefab",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441801.png",
    brief="火力全开的弹幕制造者，射速惊人，适合压制僵尸潮涌。"
}
return data