local data=
{
    BonusID=63,
    BonusPrerequisite=
    {
        62
    },
    BonusName="散射II",
    BonusCategory=2,
    BonusType=0,
    BonusPlantTarget=2,
    BonusPlantNameTargetValue="MachineGunPeaShooter",
    BonusSelectType=0,
    BonusList=
    {
        {
            BonusValue=3,
            BonusValueType=1,
            BonusOperation=2,
            BonusPlantAttributeType=0,
            BonusPlantAttribute=9,
            BonusHasDuration=false
        },
        {
            BonusValue=86,
            BonusValueType=0,
            BonusOperation=1,
            BonusPlantAttributeType=1,
            BonusBulletAttribute=3,
            BonusHasDuration=false
        }
    },
    BonusQuality=1,
    BonusIcon="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0441801.png",
    BonusDescription="机枪射手每发子弹变为3发的锥形散射弹，每颗造成60%原伤害",
    BonusFooter=""
}
return data