local data=
{
    plantType=1,
    maxHealth=100,
    damage=150,
    magazine=1,
    magazineCarry=30,
    bulletName="ChilliPea",
    bulletRange=10000,
    bulletSpeed=4000,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="",
    fireVFXScale=Vector3.New(1,1,1),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440701.png",
    brief="投掷火辣弹丸，爆炸造成范围爆炸并留下燃烧区域，是集群清除与持续压制的双重利器。"
}
return data