local data=
{
    bulletType=1,
    bulletEffect=0,
    explosionRange=Vector3.New(550,550,550),
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.5,
        frequency=200,
        strength=5,
        rotX=10,
        rotY=10,
        rotZ=0,
        posX=10,
        posY=10,
        posZ=0
    },
    hasDerive=false,
    trailVFXAssetID="sandboxId://PVZ_VFX/Prefab/M79_Trail.prefab",
    trailVFXScale=Vector3.New(1.2,1.2,1.2),
    hitVFXAssetID="sandboxId://PVZ_VFX/Prefab/M79_Hit_new.prefab",
    hitVFXScale=Vector3.New(2,2,2),
    hitGroundVFXAssetID="sandboxId://PVZ_VFX/Prefab/M79_Hit_new.prefab",
    hitGroundVFXScale=Vector3.New(2,2,2),
    hitSoundAssetID="sandboxId://PVZ_AU/CherryHowitzer/CherryHowitzer_hit.mp3",
    hitSoundAssetVolume=1,
    hitGroundSoundAssetID="",
    hitGroundSoundAssetVolume=1,
    parabolaSign=false,
    parabolaMaxDeg=0
}
return data