local data=
{
    bulletType=1,
    bulletEffect=1,
    explosionRange=Vector3.New(300,300,300),
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=20,
        rotY=20,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    hasDerive=true,
    deriveName="ChilliPeaDerive",
    deriveSplitNum=1,
    trailVFXAssetID="sandboxId://PVZ_VFX/Prefab/ChilliPitcher/ChilliPitcher_Trail.prefab",
    trailVFXScale=Vector3.New(1,1,1),
    hitVFXAssetID="sandboxId://PVZ_VFX/Prefab/ChilliPitcher/ChilliPitcher_Brust.prefab",
    hitVFXScale=Vector3.New(1,1,1),
    hitGroundVFXAssetID="sandboxId://PVZ_VFX/Prefab/ChilliPitcher/ChilliPitcher_Brust.prefab",
    hitGroundVFXScale=Vector3.New(1,1,1),
    hitSoundAssetID="sandboxId://PVZ_AU/ChilliPitcher/ChilliPitcher_explode.mp3",
    hitSoundAssetVolume=1,
    hitGroundSoundAssetID="",
    hitGroundSoundAssetVolume=1,
    parabolaSign=false,
    parabolaMaxDeg=0
}
return data