local data=
{
    plantType=2,
    maxHealth=100,
    damage=400,
    magazine=1,
    magazineCarry=20,
    bulletName="CoconutPea",
    bulletRange=10000,
    bulletSpeed=6500,
    shootConfig=
    {
        needCharge=false,
        isLoopFire=false,
        autoFireDis=0,
        autoAimDis=0
    },
    shakeConfig=
    {
        easing="Linear",
        easingStart=1,
        easingEnd=0,
        duration=0.05,
        frequency=0.05,
        strength=1,
        rotX=0,
        rotY=0,
        rotZ=0,
        posX=0,
        posY=0,
        posZ=0
    },
    fireVFXAssetID="sandboxId://PVZ_VFX/Prefab/CoconutRocket/CoconutRocket_Fire.prefab",
    fireVFXScale=Vector3.New(2,2,2),
    chargeVFXAssetID="",
    chargeVFXScale=Vector3.New(1,1,1),
    upgradeCoefficient=
    {

    },
    avatarIconAssetID="sandboxId://PVZ_UI/Common/Icon/Plants/Plant_S/Plants_S_0440601.png",
    brief="火力爆表的重型单位，一发爆炸覆盖整片区域，适合攻坚破点。"
}
return data